Repository dmsSeason11/Semi-Wiki_Backend, pull requests merged in 2025-08, with the labels that each got.

#28 fix/26 GlobalException오류 수정
  src/main/java/com/example/semiwiki_backend/global/handler/GlobalExceptionHandler.java
Labels: bug

#33 fix: (#32) jwtTokenFilter 코드 수정
  src/main/java/com/example/semiwiki_backend/global/security/config/SecurityConfig.java
  src/main/java/com/example/semiwiki_backend/global/security/jwt/JwtTokenFilter.java
Labels: enhancement

#35 fix: (#34) 학번이 같을 때 exception 수정
  src/main/java/com/example/semiwiki_backend/domain/auth/exception/StudentNumAlreadyExistsException.java
  src/main/java/com/example/semiwiki_backend/domain/auth/service/SignUpService.java
  src/main/java/com/example/semiwiki_backend/domain/user/repository/UserRepository.java
  src/main/java/com/example/semiwiki_backend/global/exception/ErrorCode.java
  src/main/java/com/example/semiwiki_backend/global/handler/GlobalExceptionHandler.java
Labels: enhancement

#47 feat/46 update header to all
  src/main/java/com/example/semiwiki_backend/domain/notice_board/controller/NoticeBoardController.java
  src/main/java/com/example/semiwiki_backend/domain/notice_board/dto/response/NoticeBoardDetailResponseDto.java
  src/main/java/com/example/semiwiki_backend/domain/notice_board/entity/NoticeBoard.java
  src/main/java/com/example/semiwiki_backend/domain/notice_board/repository/NoticeBoardHeaderRepository.java
  src/main/java/com/example/semiwiki_backend/domain/notice_board/service/NoticeBoardGetDetailService.java
  src/main/java/com/example/semiwiki_backend/domain/notice_board/service/NoticeBoardHeaderUpdateService.java
  src/main/java/com/example/semiwiki_backend/domain/notice_board/service/NoticeBoardUpdateService.java
  src/main/java/com/example/semiwiki_backend/domain/user/controller/UserController.java
Labels: feature
